---
title: "pr7сайт"
---

# Standoff 11 на PHDays 2023

### Что такое Standoff 11?

Standoff 11 --- киберучения, в которых специалисты по ИБ проверяют защищенность систем безопасности разных отраслей на примере виртуального Государства F.

Команды атакующих --- красные --- ищут уязвимости в системах государства и пытаются реализовать недопустимые события. Им противостоят синие команды защиты, которые должны максимально быстро отследить атаку и расследовать инци

### Что было?

В 2023 году турнир Standoff 11 шел четыре дня:

-   17--18 мая проходила закрытая часть кибербитвы, на которой команды хакеров изучали уязвимости в инфраструктурах компаний и реализовывали первые недопустимые события.

-   19--20 мая в хакерском замке на набережной в Парке Горького прошла открытая часть. Все посетители фестиваля могли наблюдать, как хакеры атакуют системы организаций, а защитники расследуют инциденты.

### Участники

#### Защитники

-   **BIGBRO** - защищали банковскую систему

-   **City_F\|guard** - защищали транспортную компанию Heavy Logistics

-   **Command and Defend** - защищали металлургический комбинат «МеталлиКО»

-   **CyberNoobs** - защищали электроэнергетику

-   **GISCYBERTEAM** - Защищали нефтегазовую компанию Tube

-   **SlashИточка** - защищали атомную компанию Atomic Energy

-   **Your shell not pass** - защищали управляющую компанию City

#### Атакующие

-   **Codeby**

-   **True0xA3**

-   **Bulba Hackers**

-   **DRT & ℭ𝔲𝔩𝔱**

-   **DeteAct × SPbCTF**

-   **5HM3L**

-   **TSARKA**

-   **EvilBunnyWrote**

-   **Wardagen**

-   **Invuls**

-   **Wetox**

-   **Инфосистемы Джет**

-   **APTeam**

-   **LocalGhost**

-   **RedGreen**

-   **Nomads**

-   **r3kapig**

-   **Baguette2Pain**

-   **PVG-CHRT**

-   **ActivateWindows**

-   **Straw Hat**

-   **Flaggermeister**

### Статистика

|                    | Атаки | Расследования |
|--------------------|-------|---------------|
| Банковская система | 16    | 12            |
| «МеталлиКО»        | 10    | 4             |
| Heavy Logistics    | 10    | 3             |
| УК City            | 9     | 4             |
| Электроэнергетика  | 8     | 6             |
| Atomic Energy      | 7     | 5             |
| Tube               | 3     | 3             |
| Всего              | 63    | 37            |

| Команда защитников      | **Расследовано событий** | **Зафиксировано событий** | **Зафиксировано инцидентов** | **Ошибочно зафиксировано инцидентов** | **Среднее время расследования** |
|------------|------------|------------|------------|------------|------------|
| BIGBRO                  | 17                       | 43                        | 1                            | 0                                     | 7 ч 26 мин                      |
| City_F\|guard           | 3                        | 16                        | 109                          | 0                                     | 10 ч 26 мин                     |
| Command and Defend      | 4                        | 37                        | 84                           | 1                                     | 11 ч 32 мин                     |
| CyberNoobs              | 11                       | 25                        | 63                           | 0                                     | 13 ч 48 мин                     |
| GISCYBERTEAM            | 7                        | 10                        | 248                          | 1                                     | 9 ч 13 мин                      |
| SlashИточка             | 15                       | 28                        | 53                           | 0                                     | 3 ч 11 мин                      |
| **Your shell not pass** | 8                        | 45                        | 145                          | 2                                     | 8 ч 40 мин                      |

Топ-5 Атакующих

| Место | Команда              | Реализовано недопустимых инцидентов | Баллы за недопустимые события | Баллы за уязвимости | Всего баллов |
|------------|------------|------------|------------|------------|------------|
| 1     | **Codeby**           | 46                                  | 190854                        | 2600                | 193454       |
| 2     | **True0xA3**         | 28                                  | 140689                        | 2725                | 143264       |
| 3     | **Bulba Hackers**    | 12                                  | 56671                         | 2125                | 58796        |
| 4     | **DRT & ℭ𝔲𝔩𝔱**       | 21                                  | 53950                         | 1675                | 55626        |
| 5     | **DeteAct × SPbCTF** | 17                                  | 33603                         | 2975                | 36578        |

### Комментарии участников и зрителей

> На прошедшем Standoff 11 участники команды GIS CyberTeam защищали сегмент Tube виртуального города, занимающийся добычей, переработкой, хранением и сбытом нефти и газа. «Прощупывание» инфраструктуры, инциденты ИБ, а также атаки от двадцати двух команд атакующих начали поступать уже в первый день соревнований. Члены команд защитников, по традиции соревнований, не имели возможности отражать действия атакующих и расследовали атаки с защищаемых хостов в SIEM, отслеживали действия пользователей в ASAP, сетевые атаки в PT NAD, атаки на веб-приложения в PT AF и выявляли использование вредоносного ПО с помощью PT Sandbox.
>
> Члены нашей команды учли опыт предыдущих соревнований и приняли решение разделиться на три линии SOC -- первая линия искала возможные инциденты ИБ в общем потоке трафика атакующих и передавала второй линии для сбора доказательств атаки и подготовки отчета или определения инцидента как ложного. Третья линия занималась сложными случаями атак, расследованием недопустимых событий и построением цепочки продвижения атакующих в инфраструктуре. Благодаря разделению обязанностей в соответствии с компетенциями и опытом участников, наша команда смогла зафиксировать 255 инцидентов информационной безопасности, и расследовать 70% реализованных атак, что стало одном из лучших результатов за всю историю нашего участия в соревновании.
>
> Кибербитва каждый раз поднимает участников на новый уровень -- за четыре дня интенсивной работы в условиях жесткой нехватки времени при переключении от одной атаки к другой, каждый член команды научился самостоятельно определять критичность инцидентов, проводить расследования, понимать основные направления и методики атакующих, чтобы в дальнейшем применять эти знания в своей работе. 
>
> **Никита Платов, участник команды «GISCYBERTEAM»**

> ... команда Codeby изменила параметры ректификационной колонны, из-за чего произошло ее захлебывание. В итоге нефтеперерабатывающий завод стал производить некондиционный продукт, который нельзя реализовать.
>
> Этой же команде атакующих удалось произвести крупнейшую атаку --- парализовать работу нефтепродуктопровода. Была остановлена перекачка топлива в аэропорт, поскольку авиационный керосин поставляется через этот нефтепродуктопровод. Так как остатки топлива быстро иссякли, были отменены многие транзитные рейсы. Аналогичный случай, к слову, произошел в Америке летом 2021 года с нефтепродуктопроводом Colonial Pipeline.
>
> ...
>
> Победителями киберучений со стороны атакующих стала команда Codeby (27 715 баллов), на втором месте True0xA3 (23 381 балл) и на третьем --- Invuls (12 352 балла). За четыре дня учений атакующие сдали 295 отчетов об уязвимостях. Около 40% всех отчетов сданы тремя командами: Codeby, DeteAct и Bulba Hackers. Наибольшее количество уязвимостей обнаружено в транспортной компании Heavy Logistics.
>
> Команды защитников за четыре дня предоставили 287 отчетов об инцидентах и 10 отчетов о расследованиях. Больше всего отчетов сдала команда ZoneZone. Минимальное время расследования составило 1 час 13 минут, а среднее --- 9 часов 15 минут. **CarpeDiem "Самое интересное с PHDays 2022", Хабр**

> Когда я первый раз участвовал в Standoff, мы встретились с огромным количеством инцидентов, которые нечасто увидишь, пока твой SOC не имеет много заказчиков. Здесь же, действительно, за несколько дней можно прокачаться и увидеть то, с чем не столкнешься за пару лет работы. ...
>
> Во время пентестов реального заказчика никто не даст остановить колесо обозрения или „сломать" атомную станцию. На Standoff есть возможность дойти до конца: украсть деньги, нарушить работу нефтеперерабатывающего завода или металлургического комбината. „Красным" это интересно: они могут реализовать большинство своих задумок без каких-либо ограничений. **Антон Калинин, руководитель группы экспертного обучения и наставничества Innostage\
> **(Взято с https://www.securitylab.ru/blog/company/pt/352879.php)

> Компания, участвующая в учениях на киберполигоне, предоставляет свою реальную IT-инфраструктуру, чтобы пройти своеобразный пентест и посмотреть, насколько защищены ее программно-аппаратные комплексы. Это тот маркер, который позволяет взглянуть на системы с точки зрения уязвимых мест и понять, как не допустить реализацию основных для бизнеса рисков. **Дмитрий Кузеванов, начальник службы ИБ «Азбуки вкуса»** (Взято с https://www.securitylab.ru/blog/company/pt/352879.php)
